[package]
name = "golem"
version = "0.1.0"
authors = ["Ryan Goldstein <ryan@ryanisaacg.com>"]
edition = "2018"

[dependencies]
bytemuck = "1"
glow = "0.3.0-alpha2"
mint = "0.5.3"

[dev-dependencies]
blinds = { path = "0.1.0-alpha1", features = ["gl"] }
